### ISSUE TITLE
Is it compatible with ui router $stateParams?

### ISSUE THREAD

**Issue by Emnalyeriar** [door3/angular-css#4]
Is it possible to return a string from a function to the css property in ui router? Because I would like to use the $stateParams to set the path to css file. Something like this:

    .state('State', {
        url: '/page/:id',
        controller: 'Ctrl',
        templateUrl: function($stateParams){
            return $stateParams.id+'/views/index.html';
        },
        css: function($stateParams) {
            console.log($stateParams);
            return $stateParams.id+'/styles/main.css'
        }
    });

**Comment by alexandercastillo** [comment]
Hi Emnalyeriar,

This is not possible in the current version but I'll mark it an an enhancement and release it on the next version.

Thanks!

Alex

**Comment by Emnalyeriar** [comment]
Right now I am injecting the $stateParams into my controller and set the css there, everything works fine but the page blinks for a sec before the css is added and then the elements are repositioned. Tried to add ng-cloak to my body tag but that didn't help. Any tips how to deal with that?
Thanks for setting this as an enhancement.

**Comment by alexandercastillo** [comment]
The problem with injecting in the controller is that the view loads first and then the service function is executed. That's why I recommend to use the routes and directive approach. That being said, I'll try to find a way to solve this issue for controllers.

Your enhancement should be ready between tomorrow and Friday.

Thanks!
